#!/usr/bin/env python3
"""Render LaTeX tables for the GWAYA v3 report directly from results JSON (no hand-copied numbers)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ev = json.loads((ROOT / "results/gwaya_v3_oracle_eval.json").read_text())


def tt(s: str) -> str:
    return "\\texttt{" + s.replace("_", "\\_") + "}"


lines = [
    "% AUTO-GENERATED by scripts/build_gwaya_v3_paper_tables.py from results/gwaya_v3_oracle_eval.json",
    f"\\newcommand{{\\corpusSha}}{{{ev['corpus_sha256'][:16]}}}",
    f"\\newcommand{{\\repeats}}{{{ev['repeats_per_case']}}}",
    f"\\newcommand{{\\leanVersion}}{{Lean {re.search(r'version ([0-9.]+)', ev['environment']['lean']).group(1)}}}",
    f"\\newcommand{{\\rustVersion}}{{{ev['environment']['rustc'].split(' (')[0]}}}",
    f"\\newcommand{{\\nInScope}}{{{ev['in_scope']['n']}}}",
    f"\\newcommand{{\\nLimit}}{{{ev['limitation_cases']['n']}}}",
    f"\\newcommand{{\\nTotal}}{{{len(ev['cases'])}}}",
    f"\\newcommand{{\\allDet}}{{{'yes' if ev['all_deterministic'] else 'no'}}}",
    "\\newcommand{\\confusionTable}{%",
    "\\begin{tabular}{lrrrrr}\\toprule",
    "Subset & $n$ & true accept & true reject & false accept & false reject\\\\\\midrule",
]
for key, name in (("in_scope", "In scope"), ("limitation_cases", "Known blind spots")):
    c = ev[key]
    lines.append(f"{name} & {c['n']} & {c['true_accept']} & {c['true_reject']} & {c['false_accept']} & {c['false_reject']}\\\\")
lines += ["\\bottomrule\\end{tabular}}", "\\newcommand{\\latencyTable}{%",
          "\\begin{tabular}{lrrr}\\toprule Gate & samples & median (ms) & p95 (ms)\\\\\\midrule"]
for lang, d in ev["latency_ms"].items():
    lines.append(f"{lang} & {d['n']} & {d['median']:.2f} & {d['p95']:.2f}\\\\")
lines += ["\\bottomrule\\end{tabular}}", "\\newcommand{\\caseTable}{%",
          "\\begin{longtable}{p{0.30\\linewidth}lllp{0.12\\linewidth}}\\toprule",
          "Case & Category & Label & Gate & Correct\\\\\\midrule\\endhead"]
for r in ev["cases"]:
    correct = "yes" if r["correct"] else "\\textbf{no}"
    tag = r["tag"].replace("_", "\\_")
    label = r["label"].replace("_", "\\_")
    lines.append(f"{tt(r['id'])} & {tag} & {label} & {'accept' if r['accepted'] else 'reject'} & "
                 f"{correct}\\\\")
lines += ["\\bottomrule\\end{longtable}}"]
out = ROOT / "papers/gwaya_v3_tables.tex"
out.write_text("\n".join(lines) + "\n")
print("wrote", out)
