#!/usr/bin/env python
"""Write papers/tables_a10_a12_part{1,2,3}.tex (revision 3.5.0) from the committed JSON files; no value is typed by hand.

Inputs: results/gwenlaya_v4/e_tpu_mathgate/{numbers_e_tpu_mathgate,abstention_a11,cascades_a12}.json
Reading rule for 'pays off' (addendum A12): cost ratio vs always-largest < 1 in BOTH the with- and without-warm-up
readings (point estimates) AND the CI of the accuracy difference does not lie wholly below zero.
"""
import json
from pathlib import Path

R = Path(__file__).resolve().parents[1] / "results/gwenlaya_v4/e_tpu_mathgate"
N = json.load(open(R / "numbers_e_tpu_mathgate.json"))["metrics"]
A = json.load(open(R / "abstention_a11.json"))
C = json.load(open(R / "cascades_a12.json"))
DOM = ["python", "rust", "math", "pooled"]
NAME = {"python": "Python", "rust": "Rust", "math": "Math", "pooled": "Pooled"}


def num(x, signed=False):
    s = f"{x:.3f}"
    if s in ("-0.000",):
        s = "0.000"
    if signed and not s.startswith("-"):
        s = "+" + s
    return s.replace("-", "$-$")


def pci(m, key, signed=False, ci=True):
    v = m.get(key)
    if v is None or v.get("point") is None:
        return "--"
    if not ci:
        return num(v["point"], signed)
    return f"{num(v['point'], signed)} [{num(v['lo'], signed)}, {num(v['hi'], signed)}]"


out = ["% generated by scripts/make_tables_350.py from results/gwenlaya_v4/e_tpu_mathgate/*.json - do not edit", ""]

# ---- A10 gate-only, 4B and 2B
hdr = "\\begin{table}[t]\\centering\\fontsize{6.3}{7.6}\\selectfont\\setlength{\\tabcolsep}{1.3pt}\n"
q4, q2 = "qwen3.5-4b-bf16", "qwen3.5-2b-bf16"
t = hdr + "\\caption{A10, gate-only with the program-of-thought math gate (answer iff the executed gate verifies). 4B: all domains; 2B: math only. CWR = confident-wrong rate over all tasks. $\\Delta$ = gate CWR minus the per-domain coverage-matched log-prob baseline (A4). 95\\% cluster bootstrap CIs.}\\label{tab:a10-gate}\n"
t += "\\begin{tabular}{llccccc}\\toprule\nTier & Domain & coverage & precision & CWR gate & CWR answer-all & $\\Delta$ vs matched log-prob\\\\\\midrule\n"
for dom in ["math", "pooled", "python", "rust"]:
    d = "domain_matched" if dom == "pooled" else dom
    cwr_all = pci(N, f"A3.cwr_all.{q4}.{dom}")
    delta = pci(N, f"A4.delta_cwr_gate_minus_b3.{q4}.{d}", True)
    t += f"4B & {NAME[dom]} & {pci(N, f'A3.cov.{q4}.{dom}')} & {pci(N, f'A3.prec.{q4}.{dom}')} & {pci(N, f'A3.cwr.{q4}.{dom}')} & {cwr_all} & {delta}\\\\\n"
t += "\\midrule\n"
t += f"2B & Math & {pci(N, f'A3.cov.{q2}.math')} & {pci(N, f'A3.prec.{q2}.math')} & {pci(N, f'A3.cwr.{q2}.math')} & -- & --\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- A10 cascade 2B -> gate -> 4B
t = hdr + "\\caption{A10, gate cascade 2B $\\to$ gate $\\to$ 4B with the program-of-thought math gate, versus always-4B. Cost ratio = cascade chip-seconds / always-4B chip-seconds; programs are charged to the cascade for each tier consulted. ``no warm-up'' drops the first chunk of every model (S2, post hoc). Selective: coverage and CWR of the cascade's final answer when it abstains if the 4B gate does not verify.}\\label{tab:a10-casc}\n"
t += "\\begin{tabular}{lcccccc}\\toprule\nDomain & acc.\\ 4B & acc.\\ cascade & $\\Delta$ acc.\\ (casc.$-$4B) & cost ratio & cost ratio, no warm-up & escalated\\\\\\midrule\n"
for dom in DOM:
    t += (f"{NAME[dom]} & {pci(N, f'A5.acc_large.{dom}', ci=False)} & {pci(N, f'A5.acc_cascade.{dom}', ci=False)} & {pci(N, f'A5.d_acc_cascade_minus_large.{dom}', True)} & "
          f"{pci(N, f'A5.cost_ratio_cascade_over_large.{dom}')} & {pci(N, f'S2.cost_ratio_cascade_over_large_nowarm.{dom}')} & {pci(N, f'A5.escalated.{dom}', ci=False)}\\\\\n")
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- A11, 4B
def a11(tier, name):
    m = A[tier]
    t = hdr + f"\\caption{{A11 ({name}), 5-fold cross-fitted out-of-fold scores. M0: gate verdict alone; M1: mean log-prob only; M3: logistic regression on all features (includes the gate verdict, so M3$-$M1 is a calibration gain, not independent evidence). Point [95\\% cluster bootstrap CI of fixed out-of-fold predictions]. ECE: 15 equal-mass bins; AURC: lower is better.}}\\label{{tab:a11-disc-{name[:2]}}}\n"
    t += "\\begin{tabular}{lcccccc}\\toprule\nDomain & AUROC M0 & AUROC M1 & AUROC M3 & AURC M1 & AURC M3 & ECE M3\\\\\\midrule\n"
    for dom in DOM:
        t += (f"{NAME[dom]} & {pci(m, f'disc.auroc.M0.{dom}')} & {pci(m, f'disc.auroc.M1.{dom}')} & {pci(m, f'disc.auroc.M3.{dom}')} & "
              f"{pci(m, f'disc.aurc.M1.{dom}')} & {pci(m, f'disc.aurc.M3.{dom}')} & {pci(m, f'disc.ece.M3.{dom}')}\\\\\n")
    t += "\\bottomrule\\end{tabular}\\end{table}\n"
    return t

out.append(a11(q4, "4B"))

m = A[q4]
t = hdr + "\\caption{A11 (4B), target-risk operating points: realised coverage and realised selective risk P(wrong $\\mid$ answered), pooled over the outer folds; threshold chosen inside each training portion for $\\alpha\\in\\{0.05,0.10\\}$. M1 never met $\\alpha=0.05$ (coverage 0 in every domain, risk undefined). Gate: no threshold. Point [95\\% CI].}\\label{tab:a11-op}\n"
t += "\\begin{tabular}{lcccccc}\\toprule\n & \\multicolumn{2}{c}{M3, $\\alpha=0.05$} & \\multicolumn{2}{c}{M3, $\\alpha=0.10$} & \\multicolumn{2}{c}{gate}\\\\\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\nDomain & coverage & risk & coverage & risk & coverage & risk\\\\\\midrule\n"
for dom in DOM:
    t += (f"{NAME[dom]} & {pci(m, f'op.cov.M3@0.05.{dom}')} & {pci(m, f'op.risk.M3@0.05.{dom}')} & {pci(m, f'op.cov.M3@0.1.{dom}')} & {pci(m, f'op.risk.M3@0.1.{dom}')} & "
          f"{pci(m, f'op.cov.gate.{dom}')} & {pci(m, f'op.risk.gate.{dom}')}\\\\\n")
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- A12 9B tier summary
q9 = "qwen3.5-9b-bf16"
M = C["4B_to_9B"]["metrics"]
t = hdr.replace("6.3}{7.6}", "5.6}{7}") + "\\caption{A12, Qwen3.5-9B (bf16, v5litepod-4, TP=4) alone. Pass rate, share of generations cut at 1,024 tokens, executed-gate coverage, precision and CWR, and the oracle router over the three tiers (accuracy, and its chip-seconds per task, picking the cheapest correct tier; a ceiling, not a comparator). 95\\% cluster bootstrap CIs.}\\label{tab:a12-9b}\n"
t += "\\begin{tabular}{lccccccc}\\toprule\nDomain & pass rate & truncated & gate coverage & gate precision & gate CWR & oracle acc. & oracle cost\\\\\\midrule\n"
for dom in DOM:
    O = C["oracle_router_ceiling_3tier"]
    t += (f"{NAME[dom]} & {pci(M, f'A1.acc.{q9}.{dom}')} & {pci(M, f'A9.trunc.{q9}.{dom}', ci=False)} & {pci(M, f'A3.cov.{q9}.{dom}')} & {pci(M, f'A3.prec.{q9}.{dom}')} & "
          f"{pci(M, f'A3.cwr.{q9}.{dom}')} & {pci(O, f'A6.oracle_acc.{dom}')} & {pci(O, f'A6.oracle_cost.{dom}')}\\\\\n")
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- A12 cascades with the reading rule
t = "\\begin{table}[t]\\centering\\fontsize{6.3}{7.6}\\selectfont\\setlength{\\tabcolsep}{1.3pt}\n\\caption{A12, gate cascades versus always-9B, with the reading rule fixed in addendum A12. ``Pays off'' needs a cost ratio below 1 in both the with-warm-up and no-warm-up readings (point estimates) and a CI of the accuracy difference that does not lie wholly below zero. 9B effective concurrency was not measured, so its cost is less certain. Point [95\\% CI].}\\label{tab:a12-casc}\n"
t += "\\begin{tabular}{llcccc}\\toprule\nCascade & Domain & $\\Delta$ acc.\\ (casc.$-$9B) & cost ratio & cost ratio, no warm-up & pays off?\\\\\\midrule\n"
verdicts = {}
for key, label in [("2B_to_9B", "2B$\\to$9B"), ("4B_to_9B", "4B$\\to$9B"), ("ladder_2B_4B_9B", "2B$\\to$4B$\\to$9B")]:
    m = C[key]["metrics"]
    for dom in DOM:
        d = m[f"A5.d_acc_cascade_minus_large.{dom}"]
        r1 = m[f"A5.cost_ratio_cascade_over_large.{dom}"]["point"]
        r2 = m[f"S2.cost_ratio_cascade_over_large_nowarm.{dom}"]["point"]
        ok = (r1 < 1) and (r2 < 1) and (d["hi"] >= 0)
        verdicts[(key, dom)] = ok
        t += (f"{label if dom == 'python' else ''} & {NAME[dom]} & {pci(m, f'A5.d_acc_cascade_minus_large.{dom}', True)} & {pci(m, f'A5.cost_ratio_cascade_over_large.{dom}')} & "
              f"{pci(m, f'S2.cost_ratio_cascade_over_large_nowarm.{dom}')} & {'yes' if ok else 'no'}\\\\\n")
    t += "\\midrule\n" if key != "ladder_2B_4B_9B" else ""
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# out = [header, blank, a10-gate, a10-casc, a11-disc, a11-op, a12-9b, a12-casc]
HDR = out[0] + "\n"
parts = {"part1": out[2:4], "part2": out[4:6], "part3": out[6:8]}
for k, v in parts.items():
    Path(__file__).resolve().parents[1].joinpath(f"papers/tables_a10_a12_{k}.tex").write_text(HDR + "\n".join(v))
print({f"{k[0]}.{k[1]}": v for k, v in verdicts.items()})
