#!/usr/bin/env python
"""Write papers/tables_textonly380.tex and results/gwenlaya_v4/laya/spend_summary_380.json (revision 3.8.0); no value typed by hand.

Inputs: results/gwenlaya_v4/laya/textonly_a16.json (keys sets.<Eprime|Rfresh>.<tier>.*) and the spend ledger
/mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl (lines 1..24 = as of 3.7.x; later lines = added in 3.8.0).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results/gwenlaya_v4/laya"
LEDGER = Path("/mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl")
TIERS = ["qwen3.5-2b-bf16", "qwen3.5-4b-bf16", "qwen3.5-9b-bf16"]
TN = {"qwen3.5-2b-bf16": "2B", "qwen3.5-4b-bf16": "4B", "qwen3.5-9b-bf16": "9B"}
D = json.load(open(R / "textonly_a16.json"))


def num(x, signed=False, nd=3):
    s = f"{x:.{nd}f}"
    if s.startswith("-") and float(s) == 0:
        s = s[1:]
    if signed and not s.startswith("-"):
        s = "+" + s
    return s.replace("-", "$-$")


def pci(v, signed=False, nd=3):
    return f"{num(v['point'], signed, nd)} [{num(v['lo'], signed, nd)}, {num(v['hi'], signed, nd)}]"


t = ("\\begin{table}[!htbp]\\centering\\footnotesize\\setlength{\\tabcolsep}{2pt}\n"
     "\\caption{Text-only ablation of Laya's calibrator (A16; \\code{textonly\\_a16.json}), AUROC of P(correct), one seed. Isotonic map fitted on C only. "
     "95\\% paired cluster-bootstrap CIs (10,000 resamples, seed 0); descriptive, no multiplicity correction, no hypothesis is tested. "
     "$\\Delta$ columns are differences of AUROC: text-only minus raw mean log-prob; text-only minus the hand-feature logistic regression; "
     "the frozen full Laya minus text-only. On R$'$ the log-prob baseline ranks the one answer per tier with a missing \\code{mean\\_logprob} lowest (treated as $-20$); the hand-feature regression uses 0; see the text for the other convention.}\\label{tab:textonly}\n"
     "\\begin{tabular}{llrcccc}\\toprule\n"
     "Set & Tier & $n$ & text-only AUROC [CI] & text $-$ log-prob & text $-$ hand LR & full $-$ text\\\\\\midrule\n")
for sk, nm in (("Eprime", "E$'$"), ("Rfresh", "R$'$")):
    for tr in (TIERS[2], TIERS[1], TIERS[0]):
        e = D["sets"][sk][tr]
        t += (f"{nm} & {TN[tr]} & {e['n']} & {pci(e['auroc_text'])} & {pci(e['d_auroc_text_minus_logprob'], True)} & "
              f"{pci(e['d_auroc_text_minus_handlr'], True)} & {pci(e['d_auroc_full_minus_text'], True)}\\\\\n")
    if sk == "Eprime":
        t += "\\midrule\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"

t2 = ("\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n"
      "\\caption{A16, text-only AUROC within domain on E$'$ (\\code{textonly\\_a16.json}, keys \\code{auroc\\_text.math} and \\code{auroc\\_text.python}); 95\\% CI. The domain token is in the text, so a within-domain AUROC above 0.5 rules out a domain prior only, not a source or difficulty prior.}\\label{tab:textonly-dom}\n"
      "\\begin{tabular}{lcc}\\toprule\nTier & math [CI] & Python [CI]\\\\\\midrule\n")
for tr in (TIERS[2], TIERS[1], TIERS[0]):
    e = D["sets"]["Eprime"][tr]
    t2 += f"{TN[tr]} & {pci(e['auroc_text.math'])} & {pci(e['auroc_text.python'])}\\\\\n"
t2 += "\\bottomrule\\end{tabular}\\end{table}\n"
Path(ROOT / "papers/tables_textonly380.tex").write_text("% generated by scripts/make_tables_380.py - do not edit\n" + t + "\n" + t2)

Lg = [json.loads(l) for l in open(LEDGER) if l.strip()]
new = Lg[24:]
spend = {"lines_total": len(Lg), "total_usd": round(sum(x["usd_estimate"] for x in Lg), 4), "lines_3_7": 24,
         "total_3_7": round(sum(x["usd_estimate"] for x in Lg[:24]), 4), "lines_new": len(new),
         "total_new": round(sum(x["usd_estimate"] for x in new), 4),
         "textonly_items": {x["item"]: {"seconds": x["seconds"], "usd": x["usd_estimate"], "accel": x["accel"]} for x in Lg if x["item"].startswith("tpu_laya-textonly")}}
(R / "spend_summary_380.json").write_text(json.dumps(spend, indent=1))
print(spend)
