#!/usr/bin/env python
"""Write papers/tables_rfresh370.tex and papers/tables_rfresh370_spend.tex (revision 3.7.0) from committed files; no value is typed by hand.

Inputs (under results/gwenlaya_v4/laya/): laya_rfresh.json, rust_fresh_summary.json, data/build_counts_Rfresh.json,
data/rust_fresh_report.json, data/rows_Rfresh_*.jsonl, data/preds_Rfresh_calibrator.jsonl, and
/mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl (lines 22..end = lines added since 3.6.0).
Also writes results/gwenlaya_v4/laya/rfresh_gate_laya_overlap.json: per tier, whether Laya's top-k tasks (k = gate-verified count)
are exactly the gate-verified set, and the Laya score range inside and outside that set.
"""
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results/gwenlaya_v4/laya"
LEDGER = Path("/mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl")
TIERS = ["qwen3.5-2b-bf16", "qwen3.5-4b-bf16", "qwen3.5-9b-bf16"]
TN = {"qwen3.5-2b-bf16": "2B", "qwen3.5-4b-bf16": "4B", "qwen3.5-9b-bf16": "9B"}
L = json.load(open(R / "laya_rfresh.json"))
S = json.load(open(R / "rust_fresh_summary.json"))
BC = json.load(open(R / "data/build_counts_Rfresh.json"))
RP = json.load(open(R / "data/rust_fresh_report.json"))


def num(x, signed=False, nd=3):
    s = f"{x:.{nd}f}"
    if s.startswith("-") and float(s) == 0:
        s = s[1:]
    if signed and not s.startswith("-"):
        s = "+" + s
    return s.replace("-", "$-$")


def pci(v, signed=False, nd=3):
    return f"{num(v['point'], signed, nd)} [{num(v['lo'], signed, nd)}, {num(v['hi'], signed, nd)}]"


def rd(p):
    return [json.loads(l) for l in open(p) if l.strip()]


# ---- overlap of Laya's top-k with the gate-verified set (k = number verified)
preds = rd(R / "data/preds_Rfresh_calibrator.jsonl")
overlap = {}
for tr in TIERS:
    rows = rd(R / f"data/rows_Rfresh_{tr}.jsonl")
    gate = {r["task_id"]: r["gate"] for r in rows if r["arm"] == "gate_only"}
    sc = {"rs/" + p["key"][1]: p["probs"][0] for p in preds if p["tier"] == tr}
    ver = {k for k, v in gate.items() if v == "VERIFIED"}
    top = set(sorted(sc, key=lambda x: -sc[x])[:len(ver)])
    overlap[tr] = {"n": len(sc), "k_gate_verified": len(ver), "topk_equals_gate_set": top == ver,
                   "laya_min_inside_gate_set": min(sc[x] for x in ver), "laya_max_outside_gate_set": max(sc[x] for x in sc if x not in ver)}
(R / "rfresh_gate_laya_overlap.json").write_text(json.dumps(overlap, indent=1))

out = ["% generated by scripts/make_tables_370.py from results/gwenlaya_v4/laya/*.json and the spend ledger - do not edit", ""]

# ---- build summary
reasons = Counter(v.split(":")[0] if not v.startswith("ValueError") else v.split(": ")[1] for v in RP["dropped"].values())
t = "\\begin{table}[!htbp]\\centering\\small\n\\caption{Fresh Rust set R$'$ (A14), from \\code{rust_fresh_report.json} and \\code{build_counts_Rfresh.json}: " + \
    f"{RP['n_kept']} of {RP['n_kept'] + RP['n_dropped']} Exercism practice exercises kept; {RP['n_dropped']} dropped. " + \
    f"Rows for Laya: {BC['calibrator_rows']} (task $\\times$ tier) and {BC['router_rows']} router rows. Drop reasons as written in the report.}}\\label{{tab:rfresh-build}}\n"
t += "\\begin{tabular}{lr}\\toprule\nDrop reason & exercises\\\\\\midrule\n"
for k, v in sorted(reasons.items(), key=lambda kv: (-kv[1], kv[0])):
    t += k.replace("_", "\\_").replace("!=", "$\\neq$") + f" & {v}\\\\\n"
t += f"\\midrule\nTotal dropped & {RP['n_dropped']}\\\\\nKept (used) & {RP['n_kept']}\\\\\n\\bottomrule\\end{{tabular}}\\end{{table}}\n"
out.append(t)

# ---- descriptive per tier
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{R$'$ (69 Rust tasks), per tier, one greedy sample (\\code{rust_fresh_summary.json}). Pass = hidden tests pass. Gate = first test only. Precision = share of gate-verified answers that pass. Confident-wrong (CW) = gate-verified and failing, over all 69 tasks; answer-all CW = one minus accuracy. Trunc.\\ = share of generations that stopped at the 1,024-token limit.}\\label{tab:rfresh-desc}\n"
t += "\\begin{tabular}{lrrrrrrrr}\\toprule\nTier & pass & acc. & gate verified & gate precision & CW gate & CW answer-all & trunc.\\\\\\midrule\n"
for tr in TIERS:
    s = S[tr]
    t += f"{TN[tr]} & {s['pass']}/{s['n']} & {num(s['accuracy'])} & {s['gate_verified']} & {num(s['gate_precision'])} & {num(s['confident_wrong_gate'])} & {num(s['confident_wrong_answer_all'])} & {num(s['truncated_share'])}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- scores and inference
M = L["per_tier"]
t = "\\begin{table}[!htbp]\\centering\\footnotesize\\setlength{\\tabcolsep}{2pt}\n\\caption{R$'$: the frozen Laya against the comparators (\\code{laya\\_rfresh.json}). Paired cluster bootstrap (cluster = exercise), 10,000 resamples, seed 0; one-sided $p$ in Laya's favour, Holm over \\{H1, H3\\}. H1: $\\Delta$AURC, Laya minus raw log-prob. H3: $\\Delta$ selective risk, Laya minus gate, at the gate's coverage. Last column, exploratory and without multiplicity correction: $\\Delta$AUROC, Laya minus the hand-feature logistic regression. AUROC columns are the scores themselves. $n=69$, so intervals are wide.}\\label{tab:rfresh-h}\n"
t += "\\begin{tabular}{lcccccc}\\toprule\nTier & AUROC Laya / log-prob / gate / LR & H1 $\\Delta$AURC [CI] & $p_{\\text{Holm}}$, supp. & H3 $\\Delta$risk [CI] & $p_{\\text{Holm}}$, supp. & $\\Delta$AUROC vs LR [CI]\\\\\\midrule\n"
for tr in (TIERS[2], TIERS[1], TIERS[0]):
    m, inf = M[tr]["metrics"], M[tr]["inference"]
    au = " / ".join(num(m[k]["auroc"], nd=2) for k in ("laya", "raw_logprob", "gate", "hand_lr"))
    h1, h3 = inf["H1_dAURC_laya_minus_logprob"], inf["H3_dRisk_at_gate_coverage_laya_minus_gate"]
    t += (f"{TN[tr]}{' (primary)' if tr == L['meta']['primary'] else ''} & {au} & {pci(h1, True)} & {inf['H1_p_holm']:.3f} / {'yes' if inf['H1_supported'] else 'no'} & "
          f"{pci(h3, True)} & {inf['H3_p_holm']:.3f} / {'yes' if inf['H3_supported'] else 'no'} & {pci(inf['X_dAUROC_laya_minus_hand_lr'], True)}\\\\\n")
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- router
RE = L["router"]["E_prime"]  # key name kept from analyze_laya.py; the data are R'
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{R$'$, exploratory router policy with tau = " + str(RE['tau']) + " (chosen on C in 3.6.0, not re-chosen). Same definitions as Table~\\ref{tab:laya-router}; accuracy and confident-wrong rate (CWR) over 69 tasks. Cost = attributed chip-seconds per task. In \\code{laya\\_rfresh.json} these entries sit under the key \\code{router.E\\_prime}, a name inherited from the analysis script.}\\label{tab:rfresh-router}\n"
t += "\\begin{tabular}{lccc}\\toprule\nPolicy & accuracy [CI] & CWR [CI] & cost per task [CI]\\\\\\midrule\n"
for k, nm in (("router", "Router + gate cascade"), ("ladder", "Static ladder 2B$\\to$4B$\\to$9B"), ("large", "Always 9B (answer all)")):
    t += f"{nm} & {pci(RE[k + '_acc'])} & {pci(RE[k + '_cwr'])} & {pci(RE[k + '_cost'], nd=2)}\\\\\n"
t += "\\midrule\n"
t += f"Accuracy, router $-$ always-9B & \\multicolumn{{3}}{{l}}{{{pci(RE['d_acc_router_minus_large'], True)}}}\\\\\n"
t += f"Accuracy, router $-$ ladder & \\multicolumn{{3}}{{l}}{{{pci(RE['d_acc_router_minus_ladder'], True)}}}\\\\\n"
t += f"Cost ratio vs always-9B & \\multicolumn{{3}}{{l}}{{{pci(RE['cost_ratio_router_over_large'])}}}\\\\\n"
t += f"Cost ratio vs ladder & \\multicolumn{{3}}{{l}}{{{pci(RE['cost_ratio_router_over_ladder'])}}}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- A15.1 edition sensitivity and A15.2 visible-test depth dial (results/gwenlaya_v4/edition/)
ED = json.load(open(ROOT / "results/gwenlaya_v4/edition/rust_edition_sensitivity.json"))
GD = json.load(open(ROOT / "results/gwenlaya_v4/edition/rust_gate_depth.json"))
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{A15.1, stored Rust answers re-checked under edition 2021 (\\code{rust_edition_sensitivity.json}); differences are confirmed by re-running both editions on the item. No pass-to-fail flip anywhere. Flip items: " + \
    "; ".join(sorted({x for v in ED.values() for x in v['hidden_fail_to_pass']})).replace("_", "\\_") + ".}\\label{tab:edition}\n"
t += "\\begin{tabular}{llrrrrr}\\toprule\nSet & Tier & tasks & pass 2015 / 2021 & gate verified 2015 / 2021 & hidden fail$\\to$pass & hidden pass$\\to$fail\\\\\\midrule\n"
for k, v in ED.items():
    st, tr = k.split("/")
    t += f"{'R$\\prime$' if st == 'Rfresh' else st} & {TN[tr]} & {v['n']} & {v['pass_2015']} / {v['pass_2021']} & {v['gate_verified_2015']} / {v['gate_verified_2021']} & {len(v['hidden_fail_to_pass'])} & {len(v['hidden_pass_to_fail'])}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)
V = GD["validation"]
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{A15.2, visible-test depth dial on the stored Rust answers of E (\\code{rust_gate_depth.json}; edition 2015; " + \
    f"{V['usable_with_at_least_K_assertions']} of {V['tasks']} tasks have at least {V['K']} assertions; the splitter rebuilt the stored k=1 gate payload with {V['k1_rebuild_mismatches']} mismatches over {V['tasks']} tasks). " + \
    "The gate runs the first $k$ assertions. Coverage = share of tasks verified; precision = share of verified that pass; CW = verified and failing over all tasks. 95\\% cluster-bootstrap CIs (10,000, seed 0). Descriptive; not a hypothesis test.}\\label{tab:depth}\n"
t += "\\begin{tabular}{llccc}\\toprule\nTier (accuracy) & $k$ & coverage [CI] & precision [CI] & CW [CI]\\\\\\midrule\n"
for tr in ("qwen3.5-4b-bf16", "qwen3.5-9b-bf16"):
    g = GD["tiers"][tr]
    for k in (1, 2, 3):
        lab = f"{TN[tr]} ({num(g['accuracy'])})" if k == 1 else ""
        t += f"{lab} & {k} & {pci(g[f'k{k}.coverage'])} & {pci(g[f'k{k}.precision'])} & {pci(g[f'k{k}.confident_wrong'])}\\\\\n"
    if tr != "qwen3.5-9b-bf16":
        t += "\\midrule\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- spend (ledger lines added since 3.6.0 = lines 22..end)
Lg = [json.loads(l) for l in open(LEDGER) if l.strip()]
old = Lg[:21]
new = Lg[21:]
tot_all, tot_old, tot_new = (sum(x["usd_estimate"] for x in z) for z in (Lg, old, new))
spend = {"lines_total": len(Lg), "total_usd": round(tot_all, 4), "lines_3_6_0": 21, "total_3_6_0": round(tot_old, 4),
         "lines_new": len(new), "total_new": round(tot_new, 4)}
(R / "spend_summary_370.json").write_text(json.dumps(spend, indent=1))
t = "\\begin{center}\\small\\begin{tabular}{l p{8.0cm} r r}\\toprule\nTime & Item & Seconds & USD\\\\\\midrule\n"
for x in new:
    t += f"{x['ts'][:10]} {x['ts'][11:16]} & \\code{{{x['item']}}} ({x['accel'].replace(' on-demand', '')}, {x['zone']}) & {x['seconds']:,} & {x['usd_estimate']:.4f}\\\\\n"
t += f"\\midrule\n& \\textbf{{Added since 3.6.0}} ({len(new)} lines) & & \\textbf{{{tot_new:.4f}}}\\\\\n"
t += f"& Lines 1--21 (as in 3.6.0) & & {tot_old:.4f}\\\\\n"
t += f"& \\textbf{{Total}} ({len(Lg)} lines, sum of \\code{{usd\\_estimate}}) & & \\textbf{{{tot_all:.4f}}}\\\\\n\\bottomrule\\end{{tabular}}\\end{{center}}\n"

Path(ROOT / "papers/tables_rfresh370.tex").write_text("\n".join(out))
Path(ROOT / "papers/tables_rfresh370_spend.tex").write_text("% generated by scripts/make_tables_370.py - do not edit\n" + t)
print("written; spend", spend, json.dumps(overlap))
