#!/usr/bin/env python
"""Write papers/tables_laya360.tex and papers/tables_laya360_spend.tex (revision 3.6.0) from committed JSON files; no value is typed by hand.

Inputs (all under results/gwenlaya_v4/laya/ unless noted):
  laya_eprime.json, router_nowarm.json, data/pool_manifest.json, data/build_counts_*.json,
  data/preds_C_*.jsonl (+ the labelled C rows on the data disk, only to recompute the control AUROCs;
  the result is cached in controls_C.json so the tables can be rebuilt without the data disk),
  /mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl (ledger lines 12..end = lines added since 3.5.0).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results/gwenlaya_v4/laya"
LEDGER = Path("/mnt/data/home/xavkal/gwaya-data/spend_ledger.jsonl")
CROWS = Path("/mnt/data/home/xavkal/gwaya-data/laya_data/laya_calib")
TIERS = ["qwen3.5-2b-bf16", "qwen3.5-4b-bf16", "qwen3.5-9b-bf16"]
TN = {"qwen3.5-2b-bf16": "2B", "qwen3.5-4b-bf16": "4B", "qwen3.5-9b-bf16": "9B"}
E = json.load(open(R / "laya_eprime.json"))
NW = json.load(open(R / "router_nowarm.json"))
PM = json.load(open(R / "data/pool_manifest.json"))


def num(x, signed=False, nd=3):
    s = f"{x:.{nd}f}"
    if s.startswith("-") and float(s) == 0:
        s = s[1:]
    if signed and not s.startswith("-"):
        s = "+" + s
    return s.replace("-", "$-$")


def pci(v, signed=False, nd=3):
    return f"{num(v['point'], signed, nd)} [{num(v['lo'], signed, nd)}, {num(v['hi'], signed, nd)}]"


def rd(p):
    return [json.loads(l) for l in open(p) if l.strip()]


def controls():
    cache = R / "controls_C.json"
    if CROWS.exists():
        import numpy as np
        from sklearn.metrics import roc_auc_score as auc
        from scipy.stats import spearmanr
        P = lambda n: rd(R / f"data/preds_C_{n}.jsonl")
        rows = rd(CROWS / "calibrator.jsonl")
        y = np.array([r["correct"] for r in rows])
        out = {"calibrator": {}, "router": {}}
        for name, f in (("trained", "calibrator"), ("shuffled", "calibrator_sh"), ("untrained_twin", "twin_calibrator")):
            sc = {(p["key"][0], p["key"][1], p["tier"]): p["probs"][0] for p in P(f)}
            s = np.array([sc[(r["source"], r["id"], r["tier"])] for r in rows])
            strata = []
            for d in sorted({r["domain"] for r in rows}):
                for t in TIERS:
                    m = np.array([r["domain"] == d and r["tier"] == t for r in rows])
                    strata.append(float(auc(y[m], s[m])))
            out["calibrator"][name] = {"pooled": float(auc(y, s)), "strata_min": min(strata), "strata_max": max(strata),
                                       "n_strata": len(strata)}
        rr = rd(CROWS / "router.jsonl")
        for name, f in (("trained", "router"), ("shuffled", "router_sh"), ("untrained_twin", "twin_router")):
            sc = {(p["key"][0], p["key"][1]): p["probs"] for p in P(f)}
            out["router"][name] = [float(auc([r["tiers"][t] for r in rr], [sc[(r["source"], r["id"])][i] for r in rr]))
                                   for i, t in enumerate(TIERS)]
        a = [p["probs"][0] for p in P("calibrator_sh")]
        b = [p["probs"][0] for p in P("twin_calibrator")]
        out["spearman_sh_vs_twin_calibrator"] = float(spearmanr(a, b).statistic)
        cache.write_text(json.dumps(out, indent=1))
    return json.load(open(cache))


C = controls()
out = ["% generated by scripts/make_tables_360.py from results/gwenlaya_v4/laya/*.json and the spend ledger - do not edit", ""]

# ---- data and splits
cd = PM["counts_per_domain_split"]
bt, bc, be = (json.load(open(R / f"data/build_counts_{k}.json")) for k in ("train", "C", "Eprime"))
t = "\\begin{table}[!htbp]\\centering\\small\n\\caption{Data of the Laya study (A13b). Pool P: MATH train, GSM8K train and MBPP tasks not in MBPP+; split by cluster hash mod 10 (D48). Training adds all 1,536 E tasks (D49). Counts from \\code{pool_manifest.json} and \\code{build_counts_*.json}.}\\label{tab:laya-data}\n"
t += "\\begin{tabular}{lrrrr}\\toprule\nSet & math tasks & Python tasks & tasks & calibrator rows (task $\\times$ tier)\\\\\\midrule\n"
t += f"P train & {cd['math']['train']} & {cd['python']['train']} & {cd['all']['train']} & --\\\\\n"
t += f"Train = E + P train & -- & -- & {bt['tasks']} & {bt['calibrator_rows']}\\\\\n"
t += f"C (calibration, P) & {cd['math']['calib']} & {cd['python']['calib']} & {bc['tasks']} & {bc['calibrator_rows']}\\\\\n"
t += f"E$'$ (evaluation, P) & {cd['math']['eval']} & {cd['python']['eval']} & {be['tasks']} & {be['calibrator_rows']}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- per-tier metrics
M = E["per_tier"]
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{E$'$ (828 tasks), per tier, one greedy sample. Score = P(correct) of the answer. Laya = calibrator head after the isotonic map fitted on C; log-prob = $\\exp$(mean token log-prob); gate = 1 if the executed gate verified, else 0; hand LR = logistic regression on gate, mean and min log-prob, domain and tier, fitted on the same training rows. AURC: lower is better. Acc.\\ = fraction of answers correct; gate cov.\\ = fraction the gate verifies.}\\label{tab:laya-metrics}\n"
t += "\\begin{tabular}{llrrrrrr}\\toprule\nTier & Score & AUROC & AURC & ECE15 & Brier & acc. & gate cov.\\\\\\midrule\n"
for i, tr in enumerate(TIERS):
    for j, (k, nm) in enumerate((("laya", "Laya"), ("raw_logprob", "log-prob"), ("gate", "gate"), ("hand_lr", "hand LR"))):
        m = M[tr]["metrics"][k]
        extra = f"{num(M[tr]['accuracy'])} & {num(M[tr]['gate_coverage'])}" if j == 0 else " & "
        t += f"{TN[tr] if j == 0 else ''} & {nm} & {num(m['auroc'])} & {num(m['aurc'])} & {num(m['ece15'])} & {num(m['brier'])} & {extra}\\\\\n"
    if i < 2:
        t += "\\midrule\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- H1/H3
t = "\\begin{table}[!htbp]\\centering\\footnotesize\\setlength{\\tabcolsep}{2pt}\n\\caption{E$'$: the two registered primaries as tested with deviations D48 (split), D49 (training on E) and D50 (shuffled-label control withdrawn). Paired cluster bootstrap, 10,000 resamples, seed 0; one-sided $p$ in Laya's favour, Holm over \\{H1, H3\\}. H1: $\\Delta$AURC, Laya minus raw log-prob. H3: $\\Delta$ selective risk, Laya minus gate, at the gate's own coverage (Laya keeps the same number of answers). Primary tier: 9B.}\\label{tab:laya-h}\n"
t += "\\begin{tabular}{lcccc}\\toprule\nTier & H1 $\\Delta$AURC [CI] & $p_{\\text{Holm}}$, supp. & H3 $\\Delta$risk [CI] & $p_{\\text{Holm}}$, supp.\\\\\\midrule\n"
for tr in (TIERS[2], TIERS[1], TIERS[0]):
    inf = M[tr]["inference"]
    h1, h3 = inf["H1_dAURC_laya_minus_logprob"], inf["H3_dRisk_at_gate_coverage_laya_minus_gate"]
    t += (f"{TN[tr]}{' (primary)' if tr == E['meta']['primary'] else ''} & {pci(h1, True)} & {inf['H1_p_holm']:.4f} / {'yes' if inf['H1_supported'] else 'no'} & "
          f"{pci(h3, True)} & {inf['H3_p_holm']:.3f} / {'yes' if inf['H3_supported'] else 'no'}\\\\\n")
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- exploratory vs hand LR
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{E$'$, exploratory: Laya minus the logistic regression on hand-built features (gate, mean and min log-prob, domain, tier). Paired cluster bootstrap, 95\\% CI, no multiplicity correction.}\\label{tab:laya-lr}\n"
t += "\\begin{tabular}{lcc}\\toprule\nTier & $\\Delta$AUROC [CI] & $\\Delta$AURC [CI]\\\\\\midrule\n"
for tr in (TIERS[2], TIERS[1], TIERS[0]):
    inf = M[tr]["inference"]
    t += f"{TN[tr]} & {pci(inf['X_dAUROC_laya_minus_hand_lr'], True)} & {pci(inf['X_dAURC_laya_minus_hand_lr'], True)}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- controls
ca, rt = C["calibrator"], C["router"]
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{Controls on split C (AUROC). The registered criterion was 0.4 to 0.6 for the shuffled-label (SH) heads. ``Untrained twin'' = same architecture and seed, no training. Recomputed from \\code{preds\\_C\\_*.jsonl} and the labelled C rows by \\code{scripts/make\\_tables\\_360.py} (cached in \\code{controls\\_C.json}). Strata = domain $\\times$ tier (" + str(ca['trained']['n_strata']) + ").}\\label{tab:laya-ctrl}\n"
t += "\\begin{tabular}{lcccccc}\\toprule\n & \\multicolumn{2}{c}{calibrator} & \\multicolumn{3}{c}{router (per tier: 2B / 4B / 9B)} \\\\\\cmidrule(lr){2-3}\\cmidrule(lr){4-6}\nHead & pooled & range over strata & 2B & 4B & 9B\\\\\\midrule\n"
for k, nm in (("trained", "trained Laya"), ("shuffled", "SH (shuffled labels)"), ("untrained_twin", "untrained twin")):
    t += f"{nm} & {num(ca[k]['pooled'], nd=2)} & {num(ca[k]['strata_min'], nd=2)}--{num(ca[k]['strata_max'], nd=2)} & " + " & ".join(num(v, nd=2) for v in rt[k]) + "\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- router
RE = E["router"]["E_prime"]
sel = E["router"]["tau_selection_on_C"]
t = "\\begin{table}[!htbp]\\centering\\small\\setlength{\\tabcolsep}{3pt}\n\\caption{E$'$, exploratory router policy (tau = " + str(RE['tau']) + ", chosen on C as the cheapest grid value whose C accuracy is at least that of the static ladder; on C the static ladder had accuracy " + num(sel['static_ladder_acc_C']) + "). Accuracy and confident-wrong rate (CWR) are over all 828 tasks. For the ladder and the router, accuracy counts the correctness of the final candidate even where no gate verified, and CWR = answered (gate-verified) and wrong; the always-9B policy answers everything, so its CWR is one minus its accuracy. Cost = attributed chip-seconds per task, math programs charged for every tier consulted. Cost ratios: with the first compile chunk of each run, and with that chunk (" + str(NW['warmup_chunk_tasks']) + " tasks) set to zero (\\code{router\\_nowarm.json}).}\\label{tab:laya-router}\n"
t += "\\begin{tabular}{lccc}\\toprule\nPolicy & accuracy [CI] & CWR [CI] & cost per task [CI]\\\\\\midrule\n"
for k, nm in (("router", "Router + gate cascade"), ("ladder", "Static ladder 2B$\\to$4B$\\to$9B"), ("large", "Always 9B (answer all)")):
    t += f"{nm} & {pci(RE[k + '_acc'])} & {pci(RE[k + '_cwr'])} & {pci(RE[k + '_cost'], nd=2)}\\\\\n"
t += "\\midrule\n\\multicolumn{4}{l}{Differences and ratios (router)}\\\\\n"
t += f"Accuracy, router $-$ always-9B & \\multicolumn{{3}}{{l}}{{{pci(RE['d_acc_router_minus_large'], True)}}}\\\\\n"
t += f"Accuracy, router $-$ ladder & \\multicolumn{{3}}{{l}}{{{pci(RE['d_acc_router_minus_ladder'], True)}}}\\\\\n"
t += f"Cost ratio vs always-9B, with warm-up & \\multicolumn{{3}}{{l}}{{{pci(RE['cost_ratio_router_over_large'])}}}\\\\\n"
t += f"Cost ratio vs always-9B, first chunk zeroed & \\multicolumn{{3}}{{l}}{{{pci(NW['router_over_large_nowarm'])}}}\\\\\n"
t += f"Cost ratio vs ladder, with warm-up & \\multicolumn{{3}}{{l}}{{{pci(RE['cost_ratio_router_over_ladder'])}}}\\\\\n"
t += f"Cost ratio vs ladder, first chunk zeroed & \\multicolumn{{3}}{{l}}{{{pci(NW['router_over_ladder_nowarm'])}}}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- tau grid on C
t = "\\begin{table}[!htbp]\\centering\\small\n\\caption{Choice of tau on C (\\code{laya\\_eprime.json}, \\code{router.tau\\_selection\\_on\\_C}). Static ladder accuracy on C: " + num(sel['static_ladder_acc_C']) + ". Chosen: " + str(sel['chosen']) + ".}\\label{tab:laya-tau}\n"
t += "\\begin{tabular}{lrr}\\toprule\ntau & accuracy on C & cost per task on C\\\\\\midrule\n"
for k, v in sel["grid"].items():
    t += f"{k} & {num(v['acc'])} & {num(v['cost'], nd=3)}\\\\\n"
t += "\\bottomrule\\end{tabular}\\end{table}\n"
out.append(t)

# ---- spend (lines added since 3.5.0 = ledger lines 12..end)
L = [json.loads(l) for l in open(LEDGER) if l.strip()]
tot_all = sum(x["usd_estimate"] for x in L)
tot_old = sum(x["usd_estimate"] for x in L[:11])
new = L[11:]
tot_new = sum(x["usd_estimate"] for x in new)
spend = {"lines_total": len(L), "total_usd": round(tot_all, 4), "lines_3_5_0": 11, "total_3_5_0": round(tot_old, 4),
         "lines_new": len(new), "total_new": round(tot_new, 4)}
(R / "spend_summary_360.json").write_text(json.dumps(spend, indent=1))
t = "\\begin{center}\\small\\begin{tabular}{l p{8.0cm} r r}\\toprule\nTime & Item & Seconds & USD\\\\\\midrule\n"
for x in new:
    t += f"{x['ts'][:10]} {x['ts'][11:16]} & \\code{{{x['item']}}} ({x['accel']}, {x['zone']}) & {x['seconds']:,} & {x['usd_estimate']:.4f}\\\\\n".replace("_", "\\_") if False else \
        f"{x['ts'][:10]} {x['ts'][11:16]} & \\code{{{x['item']}}} ({x['accel'].replace(' on-demand', '')}, {x['zone']}) & {x['seconds']:,} & {x['usd_estimate']:.4f}\\\\\n"
t += f"\\midrule\n& \\textbf{{Added since 3.5.0}} ({len(new)} lines) & & \\textbf{{{tot_new:.4f}}}\\\\\n"
t += f"& Lines 1--11 (as in 3.5.0) & & {tot_old:.4f}\\\\\n"
t += f"& \\textbf{{Total}} ({len(L)} lines, sum of \\code{{usd\\_estimate}}) & & \\textbf{{{tot_all:.4f}}}\\\\\n\\bottomrule\\end{{tabular}}\\end{{center}}\n"
spend_tex = t

Path(ROOT / "papers/tables_laya360.tex").write_text("\n".join(out))
Path(ROOT / "papers/tables_laya360_spend.tex").write_text("% generated by scripts/make_tables_360.py - do not edit\n" + spend_tex)
print("written; spend", spend)
